name: learn-github-actions
on: [push]
jobs:
  install-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        run: sudo apt update && apt upgrade -y && apt install -y pandoc
