name: learn-github-actions
on: [push]
jobs:
  install-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y pandoc

      - name: Run pandoc
        uses: actions/checkout@v3
        run: pandoc -V papersize:a4 --highlight-style breezeDark --pdf-engine xelatex -o foo.pdf foo.md
