name: learn-github-actions
on: [push]
jobs:
  Build_PDFs:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc & fonts
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y pandoc texlive-xetex texlive-fonts-extra texlive-fonts-recommended

      - name: Checkout repo
        uses: actions/checkout@v3

      - run: mkdir -p output

      - name: Run pandoc
        run: pandoc -V papersize:a4 --highlight-style breezeDark --pdf-engine xelatex -o output/foo.pdf foo.md

      - uses: actions/upload-artifact@v3
        with:
          name: pdf_output
          path: |
            output/foo.pdf
